

steps:
  # 1. Dockerイメージのビルド
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Image'
    args: ['build', '-t', 'asia-northeast1-docker.pkg.dev/circleci-demo-484408/circle-demo/cloud-build-image', '.']

  # 2. Artifact Registryへのプッシュ
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push Image'
    args: ['push', 'asia-northeast1-docker.pkg.dev/circleci-demo-484408/circle-demo/cloud-build-image']

  # 3. 获取Digest
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: Get DIGEST
    entrypoint: bash
    args:
      - -c
      - |
        gcloud artifacts docker images describe \
          asia-northeast1-docker.pkg.dev/circleci-demo-484408/circle-demo/cloud-build-image\
          --format='value(image_summary.digest)' \
          > /workspace/digest.txt

  # 4.创建 Attestation
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: Attest
    entrypoint: bash
    args:
      - -c
      - |
        local_digest=$(cat /workspace/digest.txt)

        gcloud beta container binauthz attestations sign-and-create \
          --artifact-url="asia-northeast1-docker.pkg.dev/circleci-demo-484408/circle-demo/cloud-build-image@$local_digest" \
          --attestor="TeatAttestor" \
          --attestor-project="circleci-demo-484408" \
          --keyversion-project="circleci-demo-484408" \
          --keyversion-location="asia-northeast1" \
          --keyversion-keyring="circleci-demo-key" \
          --keyversion-key="ForSign" \
          --keyversion="1"

    
  # 5.Check 
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: Check Attestation
    entrypoint: bash
    args:
      - -c
      - |
        local_digest=$(cat /workspace/digest.txt)

        gcloud container binauthz attestations list \
          --attestor="TeatAttestor" \
          --artifact-url="asia-northeast1-docker.pkg.dev/circleci-demo-484408/circle-demo/cloud-build-image@$local_digest" \
          --attestor-project="circleci-demo-484408" \

# オプション設定
options:
  logging: CLOUD_LOGGING_ONLY # ログをCloud Loggingに集約（BigQuery分析に便利）

# # 置換変数（組み込み変数）
# substitutions:
#   _ENV: 'dev'